Repository doctrine/sql-formatter, pull requests merged in 2024-05, with the labels that each got.

#100 Modernize codebase for PHP 8
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/static-analysis.yml
  .gitignore
  composer.json
  examples/examples.php
  phpcs.xml.dist
  phpunit.xml.dist
  psalm.xml
  src/CliHighlighter.php
  src/Cursor.php
  src/HtmlHighlighter.php
  src/SqlFormatter.php
  src/Token.php
  src/Tokenizer.php
  tests/SqlFormatterTest.php
  tests/TokenizerTest.php
Labels: enhancement

#102 Parse "NOW()" like any other function
  src/Tokenizer.php
  tests/clihighlight.html
  tests/format-highlight.html
  tests/format.html
  tests/highlight.html
Labels: bug

#103 Fix -x test file permissions
  tests/SqlFormatterTest.php
  tests/clihighlight.txt
  tests/compress.txt
  tests/format-highlight.html
  tests/format.txt
  tests/highlight.html
  tests/sql.sql
Labels: Test Suite

#105 Stop being strict about coverage metadata
  phpunit.xml.dist
  tests/SqlFormatterTest.php
  tests/TokenizerTest.php
Labels: Test Suite

#101 Impl. CASE WHEN format
  src/SqlFormatter.php
  tests/clihighlight.txt
  tests/compress.txt
  tests/format-highlight.html
  tests/format.txt
  tests/highlight.html
  tests/performance.php
  tests/sql.sql
Labels: enhancement

#108 Make sure all lines are terminated by LF
  src/CliHighlighter.php
  src/HtmlHighlighter.php
  tests/SqlFormatterTest.php
Labels: Test Suite

#112 Use constants for the indentation block type
  src/SqlFormatter.php
Labels: enhancement

#110 Fix semicolon must decrease special indentation level
  src/SqlFormatter.php
  tests/clihighlight.txt
  tests/compress.txt
  tests/format-highlight.html
  tests/format.txt
  tests/highlight.html
  tests/sql.sql
Labels: bug

#115 Dedup indent level decrease code
  src/SqlFormatter.php
Labels: enhancement

#109 Format FETCH/OFFSET as top level keywords
  src/Tokenizer.php
  tests/clihighlight.txt
  tests/compress.txt
  tests/format-highlight.html
  tests/format.txt
  tests/highlight.html
  tests/sql.sql
Labels: enhancement
